name: reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🐶 Review
        # waiting reviewdog/reviewdog#1171
        # uses: reviewdog/action-eslint@v1
        run: npx eslint src --ext=ts,tsx